pretrained: '/hdd1/Guest/tb5zhh/workspace/Seg-Interact/experiments/base/checkpoints/20230723_164149-last.pth'

world_size: 1
save_epoch_freq: 5
val_epoch_freq: 1
labeling_inference_epoch: 5
update_points_num: 0

model: MinkUNet34C

train_dataset: 
  name: scannet_quantized_limited_fast
  args:
    root: /hdd1/Guest/tb5zhh/datasets/ScanNet
    split: train
    limit: 100
    transform:
      - elastic_distortion:
          distortion_params: 
            - - 0.2
              - 0.4
            - - 0.8
              - 1.6
      - random_dropout:
          dropout_ratio: 0.2
      - random_apply:
          prob: 0.2
          inner_t: point_chromatic_auto_contrast
      - random_apply:
          prob: 0.2
          inner_t: point_chromatic_translation
      - random_apply:
          prob: 0.95
          inner_t: point_chromatic_jitter
      - random_horizontal_flip:
          upright_axis: 'z'
      - random_scale:
          scale_rng: 
            - 0.9
            - 1.1
      - random_rotation:
          angle_v: 3
          angle_h: 180
          upright_axis: 'z'
      - point_chromatic_normalize: 
      - point_to_center:
      - point_cloud_size_limit:
          max_num: 200000
val_dataset:
  name: scannet_quantized_fast
  args: 
    root: /hdd1/Guest/tb5zhh/datasets/ScanNet
    split: val
    transform:
      - point_chromatic_normalize:
      - point_to_center:
inf_dataset:
  name: scannet_quantized_fast
  args: 
    root: /hdd1/Guest/tb5zhh/datasets/ScanNet
    split: train
    transform:
      - point_chromatic_normalize:
      - point_to_center:

optimizer:
  name: Adam
  args:
    lr: 0.001
    weight_decay: 0.0001

scheduler:
  name: StepLR
  args:
    step_size: 20
    gamma: 0.5

epochs: 200
train_batch_size: 6
train_num_workers: 3
val_batch_size: 2
val_num_workers: 1
seed: 0
inference_count_path: '/home/Guest/caiz/Seg-Interact/utils'
inference_save_path: '/home/Guest/caiz/labeling_inference/run1'