world_size: 1
save_epoch_freq: 5
val_epoch_freq: 1

model: 
  name: Superpoint_MAE
  args: 
    mask_level: 1
    mask_ratio: 0.6
    feature_dim: 11
    token_embed_dim: 128
    token_pad_limit: 64
    head_num: 4
    block_depth: 4
    MLP_ratio: 1.
    

train_dataset: 
  name: superpoint_scannet
  args:
    root: /data/share/datasets/ScanNet
    split: train
    # limit: 20
    transform:
      - elastic_distortion:
          distortion_params: 
            - - 0.2
              - 0.4
            - - 0.8
              - 1.6
      - random_dropout:
          dropout_ratio: 0.2
      - random_apply:
          prob: 0.2
          inner_t: point_chromatic_auto_contrast
      - random_apply:
          prob: 0.2
          inner_t: point_chromatic_translation
      - random_apply:
          prob: 0.95
          inner_t: point_chromatic_jitter
      - random_horizontal_flip:
          upright_axis: 'z'
      - random_scale:
          scale_rng: 
            - 0.9
            - 1.1
      - random_rotation:
          angle_v: 3
          angle_h: 180
          upright_axis: 'z'
      - point_chromatic_normalize: 
      - point_to_center:
      - point_cloud_size_limit:
          max_num: 200000
val_dataset:
  name: superpoint_scannet
  args: 
    root: /data/share/datasets/ScanNet
    split: val
    transform:
      - point_chromatic_normalize:
      - point_to_center:

optimizer:
  name: Adam
  args:
    lr: 0.001
    weight_decay: 0.0001

scheduler:
  name: StepLR
  args:
    step_size: 20
    gamma: 0.5

metrics:
  - mIoU
  - IoU

epochs: 200
train_batch_size: 1
train_num_workers: 3
val_batch_size: 4
val_num_workers: 2
seed: 0
