world_size: 1
save_epoch_freq: 5
val_epoch_freq: 1
train_type: pretrain
train_from: 

model:
  name: Superpoint_MAE_DAB_Pretrain
  args:
    mask_level: 1
    mask_ratio: 0.6
    feature_dim: 11
    pos_embed_hidden_dim: 128
    token_embed_dim: 128
    token_pad_limit: 80
    head_num: 4
    MLP_ratio: 1.
    dropout_prob: 0.
    droppath_prob: 0.
    encoder_depth: 6
    

    # DAB Transformer Decoder
    ffn_dim: 512
    decoder_depth: 6
    query_dim: 2
    query_num: 3200
    group_size: 10
    

train_dataset: 
  name: superpoint_scannet
  args:
    root: /data/discover-07/share/datasets/ScanNet
    split: train
    # limit: 20
    transform:
      - elastic_distortion:
          distortion_params: 
            - - 0.2
              - 0.4
            - - 0.8
              - 1.6
      - random_dropout:
          dropout_ratio: 0.2
      - random_apply:
          prob: 0.2
          inner_t: point_chromatic_auto_contrast
      - random_apply:
          prob: 0.2
          inner_t: point_chromatic_translation
      - random_apply:
          prob: 0.95
          inner_t: point_chromatic_jitter
      - random_horizontal_flip:
          upright_axis: 'z'
      - random_scale:
          scale_rng: 
            - 0.9
            - 1.1
      - random_rotation:
          angle_v: 3
          angle_h: 180
          upright_axis: 'z'
      - point_chromatic_normalize: 
      - point_to_center:
      - point_cloud_size_limit:
          max_num: 200000
val_dataset:
  name: superpoint_scannet
  args: 
    root: /data/discover-07/share/datasets/ScanNet
    split: val
    transform:
      - point_chromatic_normalize:
      - point_to_center:

optimizer:
  name: Adam
  args:
    lr: 0.01 # 0.001
    weight_decay: 0.05

scheduler:
  name: StepLR
  args:
    step_size: 20
    gamma: 0.5

criterion: temp

epochs: 100
train_batch_size: 1
train_num_workers: 1
val_batch_size: 1
val_num_workers: 1
seed: 0
