# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# PROJECT_ROOT is inferred and set by pyrootutils package in `train.py` and `eval.py`
root_dir: /data/discover-08/caiz/Seg-Interact/

# path to data directory
data_dir: /data/discover-08/caiz/Seg-Interact/code/data/

# path to logging directory
log_dir: /data/discover-08/caiz/Seg-Interact/sp_logs/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}
